import styled, { keyframes } from 'styled-components'
import { Link } from 'react-router-dom'
import { PencilSimple } from 'phosphor-react'

interface Props {
  color: string
}

interface PropsSearch {
  status: boolean
}

const fadeIn = keyframes`
 0% {
    opacity: 0;
  }
  100% {
    visibility: visible;
    opacity: 1;
  }
  `

const scaleUpHorRight = keyframes`
0% {
    -webkit-transform: scaleX(0.4);
            transform: scaleX(0.4);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
    -webkit-transform-origin: 100% 100%;
            transform-origin: 100% 100%;
  }
`

const scaleUp = keyframes`
/* ----------------------------------------------
/* ----------------------------------------------
 * Generated by Animista on 2022-6-18 13:21:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
0%{transform:scaleY(.4);transform-origin:100% 0}100%{transform:scaleY(1);transform-origin:100% 0}
`

export const Container = styled.div`
  width: 100%;
  animation: 0.5s ease-out 0s 1 ${fadeIn};
`

export const Navbar = styled.div`
  width: 100%;
  padding-top: 1.25rem;
  padding-bottom: 1.25rem;
  background: ${({ theme }) => theme.grayMedium};
  border-bottom: 1px solid ${({ theme }) => theme.gray600};
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  justify-content: space-between;
  filter: drop-shadow(0px 20px 16px #000);
`

export const GroupLog = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  padding-left: 15px;
`

export const Logo = styled.img`
  width: 210px;
`

export const VerticalBar = styled.div<Props>`
  width: 10px;
  height: 50px;
  margin-top: 2px;
  padding-left: 1px;
  border-right: 8px solid ${({ color }) => color};
  border-radius: 1px;
`

export const Description = styled.span`
  @font-face {
    font-family: Roboto-Light;
    src: url('./assets/Fonts/Roboto/Roboto-Light.ttf');
  }
  font-family: Roboto-Light;
  padding-left: 10px;
  font-size: 20px;
`

export const Options = styled.div`
  padding: 9px;
  display: inline-block;
  vertical-align: middle;
`

export const Title = styled.a`
  text-decoration: none;
  color: ${({ theme }) => theme.gray300};

  &:hover {
    color: ${({ theme }) => theme.gray200};
  }
`

export const GroupButton = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
`

export const GroupSignUp = styled(Link)`
  display: flex;
  flex-direction: row;
  align-items: center;
  padding-left: 15px;
  padding-right: 15px;
  margin-left: 10px;
`

export const Profile = styled.img`
  display: block;
  width: 50px;
  border-radius: 9999px;
  border: 2px solid white;

  padding: 0px;
  margin: 0px;
`

export const Group = styled.div`
  display: flex;
  flex-direction: row;
`

export const InputSearch = styled.input`
  color: ${({ theme }) => theme.gray100};
  font-size: 16px;
  border-radius: 5px;
  padding: 13px;
  margin-bottom: 10px;
  text-decoration: none;
  outline: none !important;
  border: 1.5px solid ${({ theme }) => theme.gray500};
  padding-left: 10vh;
  background-color: ${({ theme }) => theme.gray900};
  background-origin: content-box;
  background: url('./assets/Svg/search.svg') no-repeat 5% 50%;
  background-size: 20px;
  animation: 0.2s ${scaleUpHorRight};
  min-width: 60vh;
`

export const ModalSearch = styled.div<PropsSearch>`
  display: ${({ status }) => (status ? 'block' : 'none')};
  position: Absolute;
  top: 80px;
  width: 71vh;
  min-height: 260px;
  max-height: 483.65px;
  border-radius: 5px;
  background-color: ${({ theme }) => theme.grayMedium};
  border: 1.5px solid ${({ theme }) => theme.gray500};
  -webkit-box-shadow: 1px 1px 16px -1px rgba(0, 0, 0, 0.23);
  box-shadow: 1px 1px 16px -1px rgba(0, 0, 0, 0.23);
  padding: 3px;
  z-index: 2;
  @media (max-width: 900px) {
    width: 285px;
  }
  animation: ${scaleUp} 0.4s cubic-bezier(0.39, 0.575, 0.565, 1) both;
`

export const HeaderImage = styled.div`
  width: 100%;
  height: 130px;
  background-image: url('./assets/background/FrameGreen.png');
  background-size: cover;
  background-repeat: no-repeat;
`

export const Section = styled.section`
  max-width: 100%;
  height: 66vh;
  display: flex;
  flex-direction: row;
`

export const SectionLeft = styled.div`
  width: 60%;
`

export const SectionRight = styled.div`
  width: 100%;
`

export const GroupProfile = styled.div`
  position: relative;
  top: -50px;
  width: 50%;
  height: 50%;
  margin: auto;
  background-color: ${({ theme }) => theme.grayMedium};
  border: 1px solid ${({ theme }) => theme.gray500};
  border-radius: 12px;
  padding: 70px;

  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`

export const Body = styled.div`
  width: 70%;
  height: 50%;
  margin: auto;
  background-color: ${({ theme }) => theme.grayMedium};
  border: 1px solid ${({ theme }) => theme.gray500};
  border-radius: 12px;
  padding-left: 70px;
  padding-right: 70px;
  padding-top: 20px;
`

export const ImagemProfile = styled.img`
  width: 140px;
  border-radius: 100%;
  border: 5px solid white;
  padding: 9px;
`

export const Name = styled.h1`
  font-weight: bold;
`

export const Hr = styled.hr`
  width: 100%;
  border: 1px solid ${({ theme }) => theme.gray500};
  margin-bottom: 20px;
`

export const Status = styled.span`
  font-size: 13px;
  color: ${({ theme }) => theme.gray300};
  text-transform: uppercase;
`

export const Header = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
`

export const TitleInfoProfile = styled.h2``

export const IcoPencilSimple = styled(PencilSimple).attrs({
  size: 23,
  color: '#8D8D99',
  weight: 'fill',
  styled: {
    padding: 70,
  },
})`
  border-radius: 3px;

  &:hover {
    background-color: ${({ theme }) => theme.gray500};
  }
`

export const DescripitionIsVoid = styled.div`
  width: 100%;
  height: 50%;
  border-radius: 10px;
  border: 1px dashed white;
  display: flex;
  align-items: center;
  &:hover {
    border: 1px dashed ${({ theme }) => theme.blue500};
    color: ${({ theme }) => theme.blue200};
  }
`

export const DescripitionIsVoidText = styled.a`
  width: 100%;
  text-align: center;
`
